// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SkillTrade.DataAccess.Postgres;

#nullable disable

namespace SkillTrade.DataAccess.Postgres.Migrations
{
    [DbContext(typeof(SkillTradeDbContext))]
    [Migration("20260503195254_DefaultData")]
    partial class DefaultData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SkillTrade.DataAccess.Postgres.Models.CoursesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<int>("DurationTimeHours")
                        .HasColumnType("integer");

                    b.Property<Guid>("IdActor")
                        .HasColumnType("uuid");

                    b.Property<int>("LessonsCount")
                        .HasColumnType("integer");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("IdActor");

                    b.HasIndex("Level");

                    b.HasIndex("Title");

                    b.ToTable("Courses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f1e2d3c4-b5a6-9780-1a2b-3c4d5e6f7a8b"),
                            CreatedAt = new DateTime(2026, 5, 3, 19, 3, 30, 0, DateTimeKind.Unspecified),
                            Description = "Освой React, Node.js, MongoDB и создавай современные веб-приложения. Более 40 часов контента и 5 живых проектов.",
                            DurationTimeHours = 46,
                            IdActor = new Guid("2c84949a-ebe9-4418-aa21-1d10f739e564"),
                            LessonsCount = 3,
                            Level = "middle",
                            Price = 0m,
                            Title = "Fullstack JavaScript: от новичка до PRO"
                        },
                        new
                        {
                            Id = new Guid("9a8b7c6d-5e4f-3a2b-1c0d-9e8f7a6b5c4d"),
                            CreatedAt = new DateTime(2026, 5, 3, 19, 3, 30, 0, DateTimeKind.Unspecified),
                            Description = "NumPy, Pandas, визуализация, основы машинного обучения. Итоговый проект — анализ данных.",
                            DurationTimeHours = 28,
                            IdActor = new Guid("2c84949a-ebe9-4418-aa21-1d10f739e564"),
                            LessonsCount = 3,
                            Level = "beginner",
                            Price = 0m,
                            Title = "Python для Data Science и AI"
                        },
                        new
                        {
                            Id = new Guid("cb66dda9-afd7-4b27-84b5-9512e5653907"),
                            CreatedAt = new DateTime(2026, 5, 3, 19, 3, 30, 0, DateTimeKind.Unspecified),
                            Description = "Создание масштабируемых бэкенд-решений, Entity Framework, Docker, RabbitMQ.",
                            DurationTimeHours = 52,
                            IdActor = new Guid("2c84949a-ebe9-4418-aa21-1d10f739e564"),
                            LessonsCount = 3,
                            Level = "advanced",
                            Price = 0m,
                            Title = "C# ASP.NET Core: разработка API и микросервисы"
                        },
                        new
                        {
                            Id = new Guid("961c8891-ff88-49c8-aa05-7073c780780d"),
                            CreatedAt = new DateTime(2026, 5, 3, 19, 3, 30, 0, DateTimeKind.Unspecified),
                            Description = "Погружение в современный frontend: хуки, контекст, RTK Query, тестирование.",
                            DurationTimeHours = 34,
                            IdActor = new Guid("2c84949a-ebe9-4418-aa21-1d10f739e564"),
                            LessonsCount = 3,
                            Level = "middle",
                            Price = 0m,
                            Title = "React + TypeScript: enterprise приложения"
                        });
                });

            modelBuilder.Entity("SkillTrade.DataAccess.Postgres.Models.LessonsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("character varying(100000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdCourse")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("IdCourse");

                    b.HasIndex("Title");

                    b.ToTable("Lessons", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Content = "<h1>Введение в JavaScript</h1><p>JavaScript — это язык программирования, который используется для создания интерактивных веб-страниц. Он позволяет добавлять динамическое поведение на сайты.</p><h2>Что такое JavaScript?</h2><p>JavaScript был создан в 1995 году Бренданом Эйхом. Сегодня это один из самых популярных языков программирования в мире.</p>",
                            CreatedAt = new DateTime(2026, 5, 3, 19, 3, 30, 0, DateTimeKind.Unspecified),
                            IdCourse = new Guid("f1e2d3c4-b5a6-9780-1a2b-3c4d5e6f7a8b"),
                            Title = "Введение в JavaScript"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Content = "<h1>Переменные и типы данных</h1><p>Переменные используются для хранения данных. В JavaScript есть три способа объявления переменных: var, let и const.</p><h2>Типы данных</h2><ul><li><strong>String</strong> — строки</li><li><strong>Number</strong> — числа</li><li><strong>Boolean</strong> — true/false</li></ul>",
                            CreatedAt = new DateTime(2026, 5, 3, 19, 3, 30, 0, DateTimeKind.Unspecified),
                            IdCourse = new Guid("f1e2d3c4-b5a6-9780-1a2b-3c4d5e6f7a8b"),
                            Title = "Переменные и типы данных"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Content = "<h1>Функции в JavaScript</h1><p>Функции — это блоки кода, которые можно вызывать многократно. Они помогают избежать дублирования кода.</p><h2>Объявление функции</h2><pre><code>function greet(name) { return 'Привет, ' + name; }</code></pre>",
                            CreatedAt = new DateTime(2026, 5, 3, 19, 3, 30, 0, DateTimeKind.Unspecified),
                            IdCourse = new Guid("f1e2d3c4-b5a6-9780-1a2b-3c4d5e6f7a8b"),
                            Title = "Функции и область видимости"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Content = "<h1>Введение в Python</h1><p>Python — это высокоуровневый язык программирования, который отличается простотой и читаемостью кода. Он широко используется в науке о данных, машинном обучении и веб-разработке.</p>",
                            CreatedAt = new DateTime(2026, 5, 3, 19, 3, 30, 0, DateTimeKind.Unspecified),
                            IdCourse = new Guid("9a8b7c6d-5e4f-3a2b-1c0d-9e8f7a6b5c4d"),
                            Title = "Введение в Python"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Content = "<h1>Pandas: работа с данными</h1><p>Библиотека Pandas предоставляет мощные инструменты для анализа и обработки данных. Основные структуры: Series и DataFrame.</p><h2>Пример кода</h2><pre><code>import pandas as pd\ndf = pd.read_csv('data.csv')\nprint(df.head())</code></pre>",
                            CreatedAt = new DateTime(2026, 5, 3, 19, 3, 30, 0, DateTimeKind.Unspecified),
                            IdCourse = new Guid("9a8b7c6d-5e4f-3a2b-1c0d-9e8f7a6b5c4d"),
                            Title = "Pandas для анализа данных"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Content = "<h1>Визуализация данных</h1><p>Matplotlib и Seaborn — основные библиотеки для создания графиков и диаграмм в Python.</p><h2>Пример графика</h2><pre><code>import matplotlib.pyplot as plt\nplt.plot([1,2,3], [4,5,6])\nplt.show()</code></pre>",
                            CreatedAt = new DateTime(2026, 5, 3, 19, 3, 30, 0, DateTimeKind.Unspecified),
                            IdCourse = new Guid("9a8b7c6d-5e4f-3a2b-1c0d-9e8f7a6b5c4d"),
                            Title = "Визуализация данных"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Content = "<h1>Введение в C# и .NET</h1><p>C# — современный объектно-ориентированный язык программирования, разработанный Microsoft. .NET — это платформа для разработки приложений.</p>",
                            CreatedAt = new DateTime(2026, 5, 3, 19, 3, 30, 0, DateTimeKind.Unspecified),
                            IdCourse = new Guid("b1c2d3e4-f5a6-7b8c-9d0e-1f2a3b4c5d6e"),
                            Title = "Введение в C# и .NET"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Content = "<h1>Создание Web API</h1><p>ASP.NET Core позволяет быстро создавать REST API. Контроллеры, маршрутизация, привязка моделей.</p><h2>Пример контроллера</h2><pre><code>[ApiController]\n[Route('api/[controller]')]\npublic class UsersController : ControllerBase\n{\n    [HttpGet]\n    public IActionResult Get() { return Ok(); }\n}</code></pre>",
                            CreatedAt = new DateTime(2026, 5, 3, 19, 3, 30, 0, DateTimeKind.Unspecified),
                            IdCourse = new Guid("b1c2d3e4-f5a6-7b8c-9d0e-1f2a3b4c5d6e"),
                            Title = "ASP.NET Core Web API"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Content = "<h1>Entity Framework Core</h1><p>ORM для работы с базами данных. Подход Code First, миграции, LINQ-запросы.</p><h2>Пример модели</h2><pre><code>public class User\n{\n    public int Id { get; set; }\n    public string Name { get; set; }\n}</code></pre>",
                            CreatedAt = new DateTime(2026, 5, 3, 19, 3, 30, 0, DateTimeKind.Unspecified),
                            IdCourse = new Guid("b1c2d3e4-f5a6-7b8c-9d0e-1f2a3b4c5d6e"),
                            Title = "Entity Framework Core"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Content = "<h1>Введение в React</h1><p>React — библиотека для создания пользовательских интерфейсов. Компонентный подход, JSX, виртуальный DOM.</p><h2>Пример компонента</h2><pre><code>function Welcome() {\n    return &lt;h1&gt;Hello, React!&lt;/h1&gt;;\n}</code></pre>",
                            CreatedAt = new DateTime(2026, 5, 3, 19, 3, 30, 0, DateTimeKind.Unspecified),
                            IdCourse = new Guid("d4e5f6a7-b8c9-0d1e-2f3a-4b5c6d7e8f90"),
                            Title = "Введение в React"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Content = "<h1>TypeScript для React</h1><p>Типизация пропсов, состояния, хуков. Интерфейсы и типы.</p><h2>Пример с типами</h2><pre><code>interface Props {\n    name: string;\n    age?: number;\n}\n\nconst User: React.FC&lt;Props&gt; = ({ name, age }) => { ... }</code></pre>",
                            CreatedAt = new DateTime(2026, 5, 3, 19, 3, 30, 0, DateTimeKind.Unspecified),
                            IdCourse = new Guid("d4e5f6a7-b8c9-0d1e-2f3a-4b5c6d7e8f90"),
                            Title = "TypeScript в React"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Content = "<h1>Redux Toolkit</h1><p>Управление глобальным состоянием приложения. Срезы (slices), экшены, редюсеры.</p><h2>Пример slice</h2><pre><code>const counterSlice = createSlice({\n    name: 'counter',\n    initialState: 0,\n    reducers: {\n        increment: state => state + 1\n    }\n});</code></pre>",
                            CreatedAt = new DateTime(2026, 5, 3, 19, 3, 30, 0, DateTimeKind.Unspecified),
                            IdCourse = new Guid("d4e5f6a7-b8c9-0d1e-2f3a-4b5c6d7e8f90"),
                            Title = "Управление состоянием: Redux Toolkit"
                        });
                });

            modelBuilder.Entity("SkillTrade.DataAccess.Postgres.Models.UserCoursesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentProgress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("SubscribeTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("TotalProgress")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "CourseId")
                        .IsUnique();

                    b.ToTable("UserCourses", (string)null);
                });

            modelBuilder.Entity("SkillTrade.DataAccess.Postgres.Models.UsersEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("Role");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f07bbc78-67d1-452e-8bad-21fc146b56e3"),
                            Balance = 0.00m,
                            CreatedAt = new DateTime(2026, 5, 3, 19, 3, 30, 0, DateTimeKind.Unspecified),
                            HashPassword = "$2a$11$TqnnLCGo8zSb2z9hVzpwSetLTFxczO1ASG6f6Mn7ap7VVi4MPztbO",
                            Login = "student123",
                            Name = "student",
                            Role = "student"
                        },
                        new
                        {
                            Id = new Guid("2c84949a-ebe9-4418-aa21-1d10f739e564"),
                            Balance = 0.00m,
                            CreatedAt = new DateTime(2026, 5, 3, 19, 3, 30, 0, DateTimeKind.Unspecified),
                            HashPassword = "$2a$11$KkcWYSsG4a.G3Ax9vpK7f.VpR.AD8rp1P/tOBhMUityHntW366ZH.",
                            Login = "actor123",
                            Name = "actor",
                            Role = "actor"
                        },
                        new
                        {
                            Id = new Guid("5d03765b-47d6-4f5b-9bd8-3d41bd2f62a3"),
                            Balance = 0.00m,
                            CreatedAt = new DateTime(2026, 5, 3, 19, 3, 30, 0, DateTimeKind.Unspecified),
                            HashPassword = "$2a$11$TPVCYIUVQQ1H5DTLLjcRDOBGzPe4cAJ/rod66GzgGhrSEOFSz2k/O",
                            Login = "admin123",
                            Name = "admin",
                            Role = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
